#ifndef ERROR_STATES
#define ERROR_STATES

enum RET_CODES
{
    RET_OK = 0,
    RET_LEXICAL_ERROR = 1,
    RET_SYNTAX_ERROR = 2,
    RET_SEMANTICAL_ERROR = 3,
    RET_SEMANTICAL_RUNTIME_ERROR = 4,
    RET_SEMANTICAL_PARAMS_ERROR = 5,
    RET_SEMANTICAL_OTHER_ERROR = 6,
    RET_INTERNAL_ERROR = 99,
    WARNING_NOT_IMPLEMENTED = 404
};

#endif
